---
title: Josh Wright - Product Designer & UX Strategist
baseurl: "/"
permalink: "/:title/"
color_scheme: light
accent_color: blue
header:
  title: Josh Wright
  has_nav: true
footer:
  content: "&copy; 2023 Forthright. All rights reserved."
  links: []
  has_social: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
